version: '3.8'

services:
  # Backend API
  backend:
    build: .
    container_name: mindmate-backend
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./runs:/app/runs
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for session management (future enhancement)
  # redis:
  #   image: redis:7-alpine
  #   container_name: mindmate-redis
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped

networks:
  default:
    name: mindmate-network
